title: Viet's Logbook
email: thanhoangviet@gmail.com
description: >- 
  A logbook for Viet, son of Ngu, of the Than family. Records of adventures 
  on this irregularly shaped ellipsoid we call Earth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# social settings (specs: minima/_includes/social.html)
twitter_username: vietnam_viet
github_username:  VietThan
linkedin_username: viet-than


# Site settings
permalink: /:title/
markdown: kramdown
paginate: 8
paginate_path: "/:num/"
date_format: "%b %-d, %Y"
excerpt_separator: <!--break-->
show_excerpts: true

# GitHub Pages forced configurations:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
