site_name: Viet Than Blogging
site_url: https://vietthan.github.io
theme:
  name: material
  logo: assets/lego_me.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - blog

nav:
  - index.md
  - Blog:
    - blog/index.md
